name: test secret and ssh actions
on: [push]

jobs:
  SECRET-SSH-ACTIONS:
    runs-on: ubuntu-latest
    steps: 
      - name: 使用 ssh-action 完成远程服务登录
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          script_stop: true # 出错后不再执行之后代码
          script: | 
            pwd
            ls -a
            touch secret.txt
            echo ${{ secrets.MY_SECRET }} >>